fotobuku/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import status.urls as status
import profiles.urls as profiles
import friends.urls as friends
import stats.urls as stats
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^status/', include(status,namespace='status')),
    url(r'^profiles/', include(profiles,namespace='profiles')),
    url(r'^friends/', include(friends,namespace='friends')),
    url(r'^stats/', include(stats,namespace='stats')),
    url(r'^$', RedirectView.as_view(permanent='True', url='/status/')),
]

friends/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
    ]

profiles/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

stats/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

status/urls.py
from django.conf.urls import url
from .views import index, add_message
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_message',add_message,name='add_message')
]

friends/models.py
from django.db import models

# Create your models here.

class Friend(models.Model):
    name = models.CharField(max_length=27)        
    url = models.URLField()
    date = models.DateTimeField(auto_now_add=True)

profiles/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    Name = models.CharField(max_length=27)
    Birth_Date = models.CharField(max_length=14)
    Gender = models.CharField(max_length=10)
    Expertise = models.TextField()
    Description = models.CharField(max_length=30)
    Email = models.CharField(max_length=20)

stats/models.py
from django.db import models

# Create your models here.

status/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
        
class StatusMessage(models.Model):
  
    message = models.CharField(max_length=240)
    created_date = models.DateTimeField(auto_now_add=True)
            
    def __str__(self):
        return self.message

friends/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }

    name_attrs = {
        'class': 'form-control',
        'placeholder':'Masukan nama temanmu disini'
    }

    url_attrs = {
        'class': 'form-control',
        'placeholder':'Masukan URL temanmu disini sesuai format'
    }

    name = forms.CharField(label = 'Nama',required=True,max_length=27,widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label = 'URL' , required=True, widget=forms.TextInput(attrs=url_attrs))

status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    message_attrs = {
        'type': 'text',
        'cols': 240,
        'rows': 6,
        'class': 'status-form-textarea',
        'id' : 'status-form-textarea',
        'placeholder':'Masukan status...'
    }

    message = forms.CharField(label='', required=True, max_length=240, widget=forms.TextInput(attrs=message_attrs))
    '''
    def __init__(self):
        super(Status_Form, self).__init__()
        self.fields['message'].widget.attrs['cols'] = 240
    '''

friends/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from datetime import datetime
from .forms import Friend_Form
from .models import Friend

# Create your views here.

def index(request):
    response = {'author' : 'Kelompok 11'}
    html = 'friendlist.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['Friend_Form'] = Friend_Form
    message = Friend.objects.all()
    response['message'] = message
    return render(request, html, response)

def add_friend(request):
    response = {}
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=form.cleaned_data['name'], url=form.cleaned_data['url'])
        friend.save()
        html = 'friendlist.html'
        return HttpResponseRedirect('/friends/')
    else:
        return HttpResponseRedirect('/friends/')

profiles/views.py
from django.shortcuts import render
##from .models import Profile
name = 'John Doe'
bio = [
       {'subject': 'Birth Date',  'value': "1 Januari"},
       {'subject': 'Gender',      'value': 'Male'},
       {'subject': 'Description', 'value': 'nanti di edit'},
       {'subject': 'Email',       'value': 'john.doe@ui.ac.id'},
       ]
listexpertise = ['python','html','css']

# Create your views here.
def index(request):
##    profile = Profile.objects.first()
##    name = profile.Name
##    bio = [
##       {'subject': 'Name',  'value': profile.Name},
##       {'subject': 'Birth Date',  'value': profile.Birth_Date},
##       {'subject': 'Gender',      'value': profile.Gender},
##       {'subject': 'Expertise',   'value': profile.Expertise},
##       {'subject': 'Description', 'value': profile.Description},
##       {'subject': 'email',       'value': profile.Email},
##       ]
    response = {'bio': bio, 'name':name}
    response['expertise']= listexpertise
    return render(request, 'profilepage.html', response)

stats/views.py
from django.shortcuts import render
from profiles.views import name
from friends.models import Friend
from status.models import StatusMessage
from profiles.models import Profile

# Create your views here.
def index(request):
    response = {'name': name,
                'feed_count' : StatusMessage.objects.count(),
                'friends_count' : Friend.objects.count(),
                'last_status' : StatusMessage.objects.last()}
    return render(request, 'stats.html', response)

status/views.py
from .models import StatusMessage
from .forms import Status_Form

from django.shortcuts import render
from datetime import datetime, date
from django.http import HttpResponseRedirect
respons = {}

def index(request):
    status = StatusMessage.objects.all()
    status = status.order_by('-created_date')

    respons['status'] = status
    respons['status_form'] = Status_Form
    html = 'status/status.html'
    return render(request, html, respons)

def add_message(request):
    print("HI")
    if 'error' in respons:
        del respons['error']
    #form = Status_Form(request.POST or None)
    if(request.method == 'POST'):
        respons['message'] = request.POST['message']
        if(0<len(respons['message'])<240):
            status = StatusMessage(message=respons['message'])
            status.save()
        elif len(respons['message'])==0:
            respons['error'] = 'Batas minimal pesan adalah 1 karakter'
        else:
            respons['error'] = 'Batas maksimal pesan adalah 240 karakter'
    return HttpResponseRedirect('/status/')

friends/templates/friendlist.html
{% extends "base.html" %}

{% block title %} Friend List {% endblock %} 

{% block content %}
	<!-- Main Body -->
	<br><br><br>
	<div class="container">
		<div class="row">
			<h3> Add Friend </h3>
			<form method="POST" action="add_friend/">
				{% csrf_token %}
				{{ Friend_Form }}
				<br>
				<button type = "submit" class="btn btn-primary float-center-right"> Submit </button>
			</form>
			
	</div>
	
	<br>
	<table class="table">
	<tr>
		<th>Nama</th>
		<th>URL</th>
		<th>Dibuat Pada</th>
	</tr>
	{% for i in message %}
	<tr>
		<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
		
			<td> {{i.name}} </td>
			<td> <a href="{{i.url}}">  {{i.url}} </a> </td>
			<td> {{i.date.time}} </td>             
	</tr>
	{% endfor %}
</table>
				
{% endblock %}

			

profiles/templates/profilepage.html
{% extends "base.html" %}
{% block content %}

<style>
	.profile_round {
		display : block;
		margin : auto;
		border-radius : 50%;
	}

	.card {
		margin-top: 30px;
		margin-left: 100px;
		margin-right: 100px;
		background-color: white;
		<!-- box-sizing: border-box; -->
		<!-- border-radius: 2px; -->
		<!-- background-clip: padding-box;
		box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12); -->
	}

	.card-footer{
		margin-top: 10px;
		margin-left: 100px;
		margin-right: 100px;
		background-color: white;
		<!-- box-sizing: border-box; -->
		<!-- border-radius: 2px; -->
		<!-- background-clip: padding-box;
		box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12); -->
	}



	body {
		background-color: #EAEAEA;
	}
</style>

<body>
	<br><br>
	<div class="card-container card">
		<br>
		<div class="image" style="text-align: center">
			<br>
			<img class="profile_round" src="https://kokensupport.com/styles/simplicity_gray/theme/images/no_avatar.gif", width="150" height="150">
		</div>

		<h2 style="text-align: center; color:#000000">{{ name }}</h2>

		<style>
		table, th, td {
		  border: 10px solid white;
		  border-collapse: collapse;
		}
		th, td {
		  padding: 5px;
		  text-align: left;
		}
		</style>

		<table align="center">
			<colgroup>
    <col span="2">
  </colgroup>
			{% for biodata in bio %}
			<tr>
				<td class="subject" align ='left'>{{ biodata.subject }}</td>
				<td class="value" align =' right'>{{ biodata.value }}</td>
			</tr>


			{% endfor %}
			<tr>
            <td class="subject" align ='left'>Expertise: </td>
            <td class="value" align =' right'>
            {% for d in expertise %}
            <span class="w3-tag w3-small w3-padding-small">
            <li>{{ d }}</li>
            </span>
            {% endfor %}
            </td>
        </tr>

		</table>
		<br>
		<br>
		<br>


	</div>
</body>
{% endblock %}

stats/templates/stats.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<html lang="en">
<style>
	.profile_round {
		display : block;
		margin : auto;
		border-radius : 50%;
	}

	.card {
		margin-top: 30px;
		margin-left: 100px;
		margin-right: 100px;
		background-color: white;
		background-clip: padding-box;
		box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
	}
	
	.card-footer{
		margin-top: 10px;
		margin-left: 100px;
		margin-right: 100px;
		background-color: white;
		background-clip: padding-box;
		box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
	}

	.card-text {
		padding:10px;
	}

	.card-container {
		padding:20px;
	}

	body {
		background-color: #EAEAEA;
	}
	
	* {
		box-sizing: border-box;
	}
	
	[class*="col-"] {
		float: left;
		padding: 10px;
		<!-- border: 1px solid red; -->
	}
	
</style>

<head>
    <meta charset="UTF-8">
    <title>{{ name }} | Stats</title>
</head>

<body>
	<div class="card-container card">
		<br>
		<img class="profile_round" src="https://kokensupport.com/styles/simplicity_gray/theme/images/no_avatar.gif", width="150" height="150">
		<h1 style="text-align: center">{{ name }}</h1>
		<hr></hr>
		
		<div class="container">
			<div class="row" style="padding-left:30px">
				<div class="col-sm-4" style="card-text;font-size:17px; text-align: center; margin-left:45px"><b>Friends </b> &emsp; &emsp;{{ friends_count }} </div>
				<div class="col-sm-4" style="card-text;font-size:17px; text-align: center"><b>Feed </b> &emsp; &emsp;{{ feed_count }}</div>
			</div>
			
			<br>
			
			<div class="row" style="padding-left:30px">
				<div class="col-sm-4"> <b>Latest Post</b> </div>
			</div>
			
			<div class="row" style="padding-left:30px">
				<img class="col-sm-1.2" src="https://kokensupport.com/styles/simplicity_gray/theme/images/no_avatar.gif", width="75" height="75">
				<div class="col-sm-4" style="padding-bottom:13.5px; padding-top:20px; text-align:center-left"> <h4><b>{{ name }}</b></h4> </div>
			</div>
			
			<div class="row" style="padding-left:30px">
				<div class="col-sm-5" style="padding-bottom:5px;"> {{last_status.message}} </div>
			</div>
			
			<div class="row" style="padding-left:30px; margin-top:5px;" >
				<div class="col-sm-2" style="padding-top:0px; font-size:12px; color:#616161">{{last_status.created_date}}</div>
			</div>
		</div>
	</div>
</body>
</html>
{% endblock %}

status/templates/status/komentar.html
{% extends "base.html" %}
{% block content %}

<style>
    .status-form-textarea{
        width: 85%;
    }

    .submit{
        width: 15%;
    }
    .card {
        margin-top: 30px;
        margin-left: 100px;
        margin-right: 100px;
        <!-- box-shadow: 2px; -->
		<!-- background-clip: padding-box; -->
		background-clip: padding-box;
		box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
    }

    .no-shadow{
        box-shadow: none;
    }
	
	.card-status {
        margin-top: 30px;
        margin-left: 20px;
        margin-right: 20px;
    }
        
    .card-footer{
        margin-top: 10px;
        margin-left: 20px;
        margin-right: 20px;
        background-color: white;
    }

    .card-text {
        border-left: thick double #4286F4;
        padding:10px;
    }

    .card-container {
        padding:20px;
        background-color: white;
    }

    body {
        background-color: #EAEAEA;
    }
	
	[class*="col-"] {
		<!-- float: left;
		padding: 10px; -->
		border: 1px solid red;
	}


</style>

    <br><br><br><br>
    <div class="col-sm9">
        <div class="card-container">
            <div class = "card">
                <b>Kamu merespon ke pos ini</b>
                <div class="card-body">
                    <p class="card-text">{{message}}</p>
                </div>
                <div class="card-footer text-muted">
                    {{created_date}}
                </div>
            </div>
            <div class = "card no-shadow">
                <form id="form" method="POST" action="{% url 'status:komentar_status' %}">
                    <input type='hidden' name='id' value= {{idx}} />
                    {% csrf_token %}
                    {{ status_form }}
                    <input id="submit" type="submit" class="btn" value="Submit"><br>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

status/templates/status/status.html
{% extends "base.html" %}
{% block content %}

<style>
    .status-form-textarea{
        width: 85%;
    }

    .submit{
        width: 15%;
    }
    .card {
        margin-top: 30px;
        margin-left: 100px;
        margin-right: 100px;
        background-clip: padding-box;
        box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
    }

    .no-shadow{
        box-shadow: none;
    }
    
    .card-status {
        margin-top: 30px;
        margin-left: 20px;
        margin-right: 20px;
    }
        
    .card-footer{
        margin-top: 10px;
        margin-left: 20px;
        margin-right: 20px;
        background-color: white;
    }

    .card-text {
        border-left: thick double #4286F4;
        padding:10px;
    }

    .card-container {
        padding:20px;
        background-color: white;
    }

    body {
        background-color: #EAEAEA;
    }
    
    [class*="col-"] {
        <!-- float: left;
        padding: 10px; -->
        <!-- border: 1px solid red; -->
    }


</style>

<body>
    <br><br>
    <div class="card-container card">
        <div class="card-container">
            <div class = "card no-shadow" style="bakground-color: #EAEAEA">
                    <form id="form" method="POST" action="{% url 'status:add_message' %}">
                            {% csrf_token %}
                            {{ status_form }}
                        <input id="submit" type="submit" class="btn" value="Submit"><br>
                    </form>
            </div>

            <section name="warning">
                {% if error %}
                    <div class="card alert alert-danger text-center">
                        <div class="card-body">
                            <strong>{{error}}</strong>
                        </div>
                    </div>
                {% endif %}
            </section>

            <br>
                {% if status %}
                    {% for data in status %}
                        <div class="card-status">
                            <div class="card-body">
                                <p class="card-text">{{data.message}}</p>
                            </div>
                            <div class="card-footer text-muted">
                                {{data.created_date}}
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Belum ada data yang dimasukan</strong>
                    </div>
                {% endif %}
        </div>
    </div>
</body>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '../static/css/base.css' %}" />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap csss -->
    <title>
        Fotobuku
    </title>
</head>

<body>
    <header>
        {% include "partials/navbar.html" %}
    </header>
    <content>
		<div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </content>
    
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      console.log("HI");
      $(".btn-secondary").click(function(){
        var umessage = $('.form-control').val();
        console.log(umessage);
        $.post("{% url 'status:add_message' %}",
        {
          message: umessage,
          csrfmiddlewaretoken: '{{ csrf_token }}' 
        });
        location.reload();
      });
    </script>
</body>
</html>

templates/partials/footer.html
<div class="footer-bottom-layout card-container card" style="margin-left:160px; margin-right:160px">
    <div class="copyright-tag">Copyright ©  2017 Group 11. All Rights Reserved.</div>
</div>

templates/partials/navbar.html
<nav class="navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">FotoBuku</a>
    </div>
	<ul class="nav navbar-nav navbar-right">
		<li style="float:right"><a href="/status">Status</a></li>
		<li style="float:right"><a href="/profiles">Profile</a></li>
		<li style="float:right"><a href="/friends">Friends</a></li>
		<li style="float:right"><a href="/stats">Stats</a></li>
    </ul>
  </div>
</nav>